<?php
/**
 * @var $block Magenest\Chapter6\Block\Exercise2\CreateInstance
 */
?>
<h3>Using Construct</h3>
<span><?php var_dump($block->getProductFieldNameUsingConstruct());?></span>
<br>
<h3>Using ObjectManager</h3>
<span><?php var_dump($block->getProductFieldNameUsingObjectManager());?></span>
<br>
<h3>Using Repository</h3>
<span><?php var_dump($block->getProductFieldNameUsingRepository());?></span>